"""empty message

Revision ID: 08ed9c153c80
Revises: f3a735744cb8
Create Date: 2024-12-01 03:31:49.173473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ed9c153c80'
down_revision = 'f3a735744cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_fav_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorite_people_people_fav_name_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['people_fav_id'], ['id'])
        batch_op.drop_column('people_fav_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_fav_name', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_people_people_fav_name_fkey', 'people', ['people_fav_name'], ['id'])
        batch_op.drop_column('people_fav_id')

    # ### end Alembic commands ###
